[package]
name = "tubemusic"
version = "0.1.0"
authors = ["Huy Tran <hey@huy.rocks>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0.115"
serde = "1.0.115"
serde_json = "1.0.57"
actix-web = "3"
actix-files = "0.3"
